/**
 * Aula guiada · Qual classe usar em cada caso (módulo 23 · docs/page_07.md)
 * Analogia: a caixa de ferramentas (a chave certa para cada parafuso).
 */
Aula.registrar({
  id: 'dt-mapa', licao: 'dt-mapa',
  titulo: 'Date-Time: a chave certa para cada caso',
  personagem: { nome: 'Bean' },
  fechamento: 'java.time é imutável e thread-safe. Existe uma classe certa por pergunta, e Period é para datas, Duration para tempo.',
  cenas: [
    { fala: ['Trabalhar com data no Java tem uma caixa de ferramentas própria: `java.time`. Cada classe é a **chave certa** para um parafuso.'],
      palco(host, api) { host.innerHTML = `<div style="text-align:center"><div class="analogia" style="margin:0 auto 16px; max-width:440px"><div class="analogia-titulo">A ideia de hoje</div><div class="analogia-cena"><div class="grande">🧰</div><div>"só data? só hora? com fuso? um instante?"</div></div></div><div class="palco-titulo">Módulo 23 · Date-Time API</div><p style="color:var(--muted); max-width:400px; margin:0 auto; line-height:1.7; font-size:0.85rem">12 etapas. Analogia primeiro, código depois.</p></div>`; api.gsap.from(host.querySelector('.analogia-cena'), { y: 20, opacity: 0, duration: 0.5, ease: 'back.out(1.5)' }); } },
    { fala: ['A API antiga (`Date`, `Calendar`) era uma armadilha: mutável e com o mês começando em zero. Executa.'], interativo: true, emocao: 'alerta', dica: 'Clique em executar',
      palco(host, api) { host.innerHTML = `<div class="analogia"><div class="analogia-titulo">Mundo real: a ferramenta velha que aperta errado</div><div class="analogia-cena"><div class="grande">🔧💥</div><div>"janeiro é... zero?"</div></div></div>${api.codigo(`Calendar c = Calendar.getInstance();
c.set(2024, 0, 15);   // janeiro é 0 (!), não 1`)}<div class="palco-escolhas"><button class="chip" id="btn">▶ que mês é 0?</button></div><div class="saida" id="saida" style="display:none"></div>`;
        host.querySelector('#btn').onclick=e=>{e.target.disabled=true;api.som('barrado');const s=host.querySelector('#saida');s.style.display='block';s.innerHTML=`<span class="erro">O mês 0 é JANEIRO. Fonte infinita de bug.</span>\n<span class="neutro">Date é mutável e não thread-safe. Por isso veio o java.time.</span>`;api.gsap.from(s,{y:10,opacity:0,duration:0.3});api.reagir('alerta');api.pronto('A API legada era mutável e confusa: o java.time nasceu para consertar isso');}; } },
    { fala: ['A pergunta que separa quem sabe:'], interativo: true,
      palco(host, api) { host.innerHTML = `<div class="palco-titulo">Checagem rápida</div><h2 style="text-align:center; margin-bottom:12px">Diferença central do <code>java.time</code> para a API antiga?</h2><div class="options"><button class="option" data-i="0"><span class="option-key">A</span><span>É mais rápido</span></button><button class="option" data-i="1"><span class="option-key">B</span><span>É <b>imutável e thread-safe</b>: cada operação devolve uma nova instância</span></button></div>`;
        const ok=1;host.querySelectorAll('.option').forEach(b=>b.onclick=()=>{const e=Number(b.dataset.i);host.querySelectorAll('.option').forEach((o,i)=>{o.classList.add('disabled');o.onclick=null;if(i===ok)o.classList.add('right');else if(i===e)o.classList.add('wrong');});api.registrarResposta(e===ok);api.pronto(e===ok?'Isso: imutável e thread-safe':'É a B: imutabilidade é a grande mudança');}); } },
    { fala: ['Cada necessidade, uma classe. Toca em cada situação para ver a ferramenta certa.'], interativo: true, dica: 'Toque nas quatro situações',
      palco(host, api) { const d={'Só data':'LocalDate (aniversário, vencimento)','Só hora':'LocalTime (horário de funcionamento)','Data e hora':'LocalDateTime (agendamento)','Com fuso':'ZonedDateTime, ou Instant para timestamp em UTC'};
        host.innerHTML = `<div class="analogia"><div class="analogia-titulo">Mundo real: relógio, calendário e agenda</div><div class="analogia-cena"><div class="grande">📅🕐🌍</div><div>"a pergunta define a classe"</div></div></div><div class="palco-escolhas">${Object.keys(d).map(k=>`<button class="chip" data-k="${k}">${k}</button>`).join('')}</div><div class="saida" id="saida">Toque para ver a classe certa</div>`;
        const s=host.querySelector('#saida');const vistos=new Set();host.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{host.querySelectorAll('.chip').forEach(x=>x.classList.remove('ativo'));c.classList.add('ativo');api.som('clique');s.innerHTML=`<span class="neutro"><b>${c.dataset.k}</b>: ${d[c.dataset.k]}</span>`;vistos.add(c.dataset.k);if(vistos.size===4)api.pronto('Uma classe por pergunta: nada de encaixar tudo num Date');}); } },
    { fala: ['Esse é o **mapa de decisão** do java.time.'],
      palco(host, api) { host.innerHTML = `<div class="palco-titulo">O conceito, agora com nome</div><table class="mini-tabela"><thead><tr><th>Preciso de</th><th>Classe</th></tr></thead><tbody><tr><td>só data</td><td>LocalDate</td></tr><tr><td>só hora</td><td>LocalTime</td></tr><tr><td>data + hora</td><td>LocalDateTime</td></tr><tr><td>com fuso</td><td>ZonedDateTime</td></tr><tr><td>instante (timestamp)</td><td>Instant (UTC)</td></tr></tbody></table><div class="note">Para gravar e trocar entre sistemas, prefira <code>Instant</code> (UTC).</div>`; api.gsap.from(host.children,{y:16,opacity:0,duration:0.4,stagger:0.12}); } },
    { fala: ['E a dupla que mais confunde: `Period` e `Duration`. Toca em cada uma.'], interativo: true, dica: 'Toque nas duas',
      palco(host, api) { const d={Period:'diferença em anos, meses e dias (baseado em DATAS)',Duration:'diferença em horas, minutos e segundos (baseado em TEMPO)'};
        host.innerHTML = `<div class="analogia"><div class="analogia-titulo">Mundo real: contar dias x contar horas</div><div class="analogia-cena"><div class="grande">📆⏱️</div><div>"idade em anos x tempo de execução em segundos"</div></div></div><div class="palco-escolhas"><button class="chip" data-k="Period">Period</button><button class="chip" data-k="Duration">Duration</button></div><div class="saida" id="saida">Toque para ver a diferença</div>`;
        const s=host.querySelector('#saida');const vistos=new Set();host.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{host.querySelectorAll('.chip').forEach(x=>x.classList.remove('ativo'));c.classList.add('ativo');api.som('clique');s.innerHTML=`<span class="neutro"><b>${c.dataset.k}</b>: ${d[c.dataset.k]}</span>`;vistos.add(c.dataset.k);if(vistos.size===2)api.pronto('Period para datas, Duration para tempo do relógio');}); } },
    { fala: ['A pegadinha de entrevista sobre esse par:'], interativo: true,
      palco(host, api) { host.innerHTML = `<div class="palco-titulo">Checagem rápida</div><h2 style="text-align:center; margin-bottom:12px">Idade de uma pessoa (anos, meses, dias): qual classe?</h2><div class="options"><button class="option" data-i="0"><span class="option-key">A</span><span><code>Duration</code></span></button><button class="option" data-i="1"><span class="option-key">B</span><span><code>Period.between(nascimento, hoje)</code></span></button></div>`;
        const ok=1;host.querySelectorAll('.option').forEach(b=>b.onclick=()=>{const e=Number(b.dataset.i);host.querySelectorAll('.option').forEach((o,i)=>{o.classList.add('disabled');o.onclick=null;if(i===ok)o.classList.add('right');else if(i===e)o.classList.add('wrong');});api.registrarResposta(e===ok);api.pronto(e===ok?'Isso: idade em datas = Period':'É Period: anos/meses/dias vêm de datas');}); } },
    { fala: ['Criar e navegar é direto, e sempre devolve nova instância.'],
      palco(host, api) { host.innerHTML = `<div class="palco-titulo">Criar e navegar</div>${api.codigo(`LocalDate hoje = LocalDate.now();
LocalDate natal = LocalDate.of(2024, 12, 25);
natal.plusDays(10);   // devolve NOVA data; natal não muda
LocalDate.parse("2024-12-25");   // ISO por padrão`)}<div class="note">Como é imutável, <code>natal.plusDays(10)</code> sozinho não muda nada: reatribua.</div>`; api.gsap.from(host.children,{y:16,opacity:0,duration:0.4,stagger:0.12}); } },
    { fala: ['ChronoUnit dá a diferença total numa unidade só.'],
      palco(host, api) { host.innerHTML = `<div class="palco-titulo">Diferença total</div>${api.codigo(`long dias = ChronoUnit.DAYS.between(inicio, fim);    // 430 dias
long meses = ChronoUnit.MONTHS.between(inicio, fim);  // 14 meses

Period p = Period.between(inicio, fim);   // 1 ano, 2 meses e 5 dias`)}<div class="note">Period quebra em anos/meses/dias; ChronoUnit dá o total numa unidade.</div>`; api.gsap.from(host.children,{y:16,opacity:0,duration:0.4,stagger:0.12}); } },
    { fala: ['Lembra da imutabilidade? Ela pega muita gente.'], interativo: true,
      palco(host, api) { host.innerHTML = `<div class="palco-titulo">Checagem rápida</div>${api.codigo(`LocalDate d = LocalDate.of(2024, 1, 1);
d.plusMonths(1);
System.out.println(d);`)}<div class="options"><button class="option" data-i="0"><span class="option-key">A</span><span><code>2024-02-01</code></span></button><button class="option" data-i="1"><span class="option-key">B</span><span><code>2024-01-01</code>: plusMonths devolveu outra data, mas ninguém guardou</span></button></div>`;
        const ok=1;host.querySelectorAll('.option').forEach(b=>b.onclick=()=>{const e=Number(b.dataset.i);host.querySelectorAll('.option').forEach((o,i)=>{o.classList.add('disabled');o.onclick=null;if(i===ok)o.classList.add('right');else if(i===e)o.classList.add('wrong');});api.registrarResposta(e===ok);api.pronto(e===ok?'Isso: imutável, precisa reatribuir':'É 2024-01-01: o retorno foi ignorado');}); } },
    { fala: ['Fecha com a escolha da classe:'], interativo: true,
      palco(host, api) { host.innerHTML = `<div class="palco-titulo">Checagem final</div><h2 style="text-align:center; margin-bottom:12px">Um timestamp para gravar no banco e trocar entre serviços. Qual usar?</h2><div class="options"><button class="option" data-i="0"><span class="option-key">A</span><span><code>LocalDateTime</code></span></button><button class="option" data-i="1"><span class="option-key">B</span><span><code>Instant</code> (UTC): ponto absoluto na linha do tempo</span></button></div>`;
        const ok=1;host.querySelectorAll('.option').forEach(b=>b.onclick=()=>{const e=Number(b.dataset.i);host.querySelectorAll('.option').forEach((o,i)=>{o.classList.add('disabled');o.onclick=null;if(i===ok)o.classList.add('right');else if(i===e)o.classList.add('wrong');});api.registrarResposta(e===ok);api.pronto(e===ok?'Perfeito: Instant em UTC para persistir/trocar':'É Instant: ponto absoluto, sem ambiguidade de fuso');}); } },
    { fala: ['Date-Time no bolso. Seis imagens.'], emocao: 'feliz',
      palco(host, api) { const cards=[['🧰','java.time','a caixa de ferramentas moderna'],['🔒','Imutável','cada operação devolve nova instância'],['📅','LocalDate/Time/DateTime','só data, só hora, os dois'],['🌍','ZonedDateTime / Instant','com fuso; Instant em UTC para persistir'],['📆','Period','datas: anos, meses, dias'],['⏱️','Duration','tempo: horas, minutos, segundos']]; host.innerHTML=`<div class="palco-titulo">O que ficou</div><div style="display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:10px">${cards.map(([i,t,d])=>`<div class="recap-card" style="background:var(--card); border:1px solid var(--border); border-radius:12px; padding:12px"><div style="font-size:1.4rem; margin-bottom:5px">${i}</div><div style="font-weight:700; font-size:0.84rem; margin-bottom:3px">${t}</div><div style="color:var(--muted); font-size:0.76rem; line-height:1.5">${d}</div></div>`).join('')}</div>`; api.gsap.from(host.querySelectorAll('.recap-card'),{y:26,opacity:0,scale:0.94,duration:0.45,stagger:0.08,ease:'back.out(1.4)'}); } },
  ],
});
